In [1]:
import numpy as np

import matplotlib.pyplot as plt

%matplotlib inline

In [15]:
def trapz(f,a,b,N=50):



    x = np.linspace(a,b,N+1)
    p = np.linspace(a,b,N+1)
    X, P = np.meshgrid(x, p)

    y = f(X, P)

    y_right = y[1:] # Right endpoints

    y_left = y[:-1] # Left endpoints
    print(y_left)
    print(y_right)
    dx = (b - a)/N
    dp = (b - a)/N

    T = (dx/2) * dp * np.sum(y_right + y_left)

    return T

In [22]:
trapz(lambda x, p : ((x-2)**2+(p-2)**2)**(-1/2),-1,1,10000)

[[0.23570226 0.23571012 0.23571797 ... 0.31621512 0.31622144 0.31622777]
 [0.23571012 0.23571797 0.23572583 ... 0.31623409 0.31624041 0.31624674]
 [0.23571797 0.23572583 0.23573369 ... 0.31625306 0.31625939 0.31626572]
 ...
 [0.31620879 0.31622776 0.31624673 ... 0.7067534  0.70682404 0.70689468]
 [0.31621512 0.31623409 0.31625306 ... 0.70682405 0.70689471 0.70696537]
 [0.31622144 0.31624041 0.31625939 ... 0.70689471 0.70696539 0.70703607]]
[[0.23571012 0.23571797 0.23572583 ... 0.31623409 0.31624041 0.31624674]
 [0.23571797 0.23572583 0.23573369 ... 0.31625306 0.31625939 0.31626572]
 [0.23572583 0.23573369 0.23574155 ... 0.31627204 0.31627837 0.3162847 ]
 ...
 [0.31621512 0.31623409 0.31625306 ... 0.70682405 0.70689471 0.70696537]
 [0.31622144 0.31624041 0.31625939 ... 0.70689471 0.70696539 0.70703607]
 [0.31622777 0.31624674 0.31626572 ... 0.70696537 0.70703607 0.70710678]]


1.4495439766415397

In [26]:
from scipy.integrate import quad, dblquad

In [24]:
def integrand(x, p):
	return ((x-2)**2 + (p -2)**2)**(-1/2)

In [27]:
dblquad(integrand, -1, 1,-1,1)

(1.4493948762686601, 1.6091515634071965e-14)